version: '3.9'

services:
    scalpel:
        image: ghcr.io/blockba5her/scalpel:{version}
        container_name: scalpel
        ports:
            - 443:443
        volumes:
            - ./settings.yaml:/mangahome/settings.yaml:ro
            - ./data/cache:/mangahome/cache
        environment:
            RUST_LOG: INFO
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "2"
