on: [push]
name: ci
env:
    CI: 1

jobs:
    build-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: install rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal

            - name: cache LLVM
              id: cache-llvm
              uses: actions/cache@v2
              with:
                  path: ${{ runner.temp }}/llvm
                  key: llvm-11
            - name: install LLVM
              uses: KyleMayes/install-llvm-action@v1
              with:
                  version: "11.1"
                  directory: ${{ runner.temp }}/llvm
                  cached: ${{ steps.cache-llvm.outputs.cache-hit }}
            
            # cache rust dependency/build directories
            - name: cache cargo
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: cache target
              uses: actions/cache@v2
              with:
                  path: target
                  key: ${{ runner.os }}-build-target-${{ hashFiles('**/Cargo.lock') }}

            - run: cargo test
            - run: cargo build --release

            - uses: actions/upload-artifact@v2
              with:
                  name: ${{ runner.os }}-scalpel
                  path: target/release/scalpel*

# TODO: Add build for windows systems
# Unfortunately, this isn't easy because LLVM for windows doesn't come with `llvm-config`, which is required
# to build RocksDB. So, we'll need to eventually build LLVM ourselves and cache it.
